TRUNCATE TABLE PRODUTOS CASCADE;
TRUNCATE TABLE VENDEDORES CASCADE;
TRUNCATE TABLE COMPRADORES CASCADE;
TRUNCATE TABLE VENDAS RESTART IDENTITY CASCADE;
TRUNCATE TABLE TRANSACOES RESTART IDENTITY CASCADE;

INSERT INTO PRODUTOS VALUES ('ARGILA', '11111111111111111111', '2020-01-01', 10.0, 1.0, 1.0, 1.0, 1.0, 1.0, 100.0);
INSERT INTO PRODUTOS VALUES ('CIMENT', '22222222222222222222', '2020-01-01', 20.0, 2.0, 2.0, 2.0, 2.0, 2.0, 100.0);
INSERT INTO PRODUTOS VALUES ('CONCRE', '33333333333333333333', '2020-01-01', 30.0, 3.0, 3.0, 3.0, 3.0, 3.0, 100.0);

INSERT INTO VENDEDORES VALUES ('IDCAR', '11111111111', 'Carlos', 'carlos@carlos.com');
INSERT INTO VENDEDORES VALUES ('IDLUI', '22222222222', 'Luis', 'luis@luis.com');
INSERT INTO VENDEDORES VALUES ('IDPED', '33333333333', 'Pedro', 'pedro@pedro.com');

INSERT INTO COMPRADORES VALUES ('GUST', '12345678901', 'Gustavo', '51111111111', 'Rua 1');
INSERT INTO COMPRADORES VALUES ('LORE', '23456789012', 'Lorenzo', '52222222222', 'Rua 2');
INSERT INTO COMPRADORES VALUES ('SORR', '34567890123', 'Sor', '53333333333', 'Rua 3');

INSERT INTO VENDAS(DATA_VENDA, ID_VENDEDOR, ID_COMPRADOR) VALUES ('2020-01-01', 'IDCAR', 'GUST'); /* VENDA 1 - CARLOS - GUSTAVO */
INSERT INTO VENDAS(DATA_VENDA, ID_VENDEDOR, ID_COMPRADOR) VALUES ('2020-01-15', 'IDPED', 'GUST'); /* VENDA 2 - CARLOS - GUSTAVO */

INSERT INTO TRANSACOES VALUES ('CONCRE', 1, 4.0); /* VENDA 1 - 4x CONCRE - TOTAL 120  */
INSERT INTO TRANSACOES VALUES ('ARGILA', 2, 1.0); /* VENDA 2 - 1x CONCRE - TOTAL 30   */

DO $$
    BEGIN
        RAISE NOTICE 'TESTE 1 - DEPENDENCIAS TABELA PRODUTOS';

        /* TESTE 1A - TENTA DELETAR PRODUTO ARGILA - DEVE FALHAR */
        BEGIN
            DELETE FROM PRODUTOS WHERE ID_PRODUTO = 'ARGILA';
            RAISE EXCEPTION 'TESTE 1A - FAIL';
        EXCEPTION
            WHEN foreign_key_violation THEN
                RAISE NOTICE 'TESTE 1A - OK';
        END;

        /* TESTE 1B - TENTA DELETAR PRODUTO CONCRE - DEVE FALHAR */
        BEGIN
            DELETE FROM PRODUTOS WHERE ID_PRODUTO = 'CONCRE'; /* VENDA 4 - 4x CIMENT - TOTAL 80   */
            RAISE EXCEPTION 'TESTE 1B - FAIL';
        EXCEPTION
            WHEN foreign_key_violation THEN
                RAISE NOTICE 'TESTE 1B - OK';
        END;

        /* TESTE 1C - TENTA DELETAR PRODUTO CIMENT - DEVE PASSAR */
        BEGIN
            DELETE FROM PRODUTOS WHERE ID_PRODUTO = 'CIMENT'; /* VENDA 5 - 3x ARGILA - TOTAL 30   */
            RAISE NOTICE 'TESTE 1C - OK';
        EXCEPTION
            WHEN OTHERS THEN
                RAISE EXCEPTION 'TESTE 1C - FAIL';
        END;
    END;
$$;

DO $$
    BEGIN
        RAISE NOTICE 'TESTE 2 - DEPENDENCIAS TABELA VENDEDORES';

        /* TESTE 2A - TENTA DELETAR VENDEDOR IDCAR - DEVE FALHAR */
        BEGIN
            DELETE FROM VENDEDORES WHERE ID_VENDEDOR = 'IDCAR';
            RAISE EXCEPTION 'TESTE 2A - FAIL';
        EXCEPTION
            WHEN foreign_key_violation THEN
                RAISE NOTICE 'TESTE 2A - OK';
        END;

        /* TESTE 2B - TENTA DELETAR VENDEDOR IDPED - DEVE FALHAR */
        BEGIN
            DELETE FROM VENDEDORES WHERE ID_VENDEDOR = 'IDPED';
            RAISE EXCEPTION 'TESTE 2B - FAIL';
        EXCEPTION
            WHEN foreign_key_violation THEN
                RAISE NOTICE 'TESTE 2B - OK';
        END;

        /* TESTE 2C - TENTA DELETAR VENDEDOR IDLUI - DEVE PASSAR */
        BEGIN
            DELETE FROM VENDEDORES WHERE ID_VENDEDOR = 'IDLUI';
            RAISE NOTICE 'TESTE 2C - OK';
        EXCEPTION
            WHEN OTHERS THEN
                RAISE EXCEPTION 'TESTE 2C - FAIL';
        END;
    END;
$$;

DO $$
    BEGIN
        RAISE NOTICE 'TESTE 3 - DEPENDENCIAS TABELA COMPRADORES';

        /* TESTE 3A - TENTA DELETAR COMPRADOR GUST - DEVE FALHAR */
        BEGIN
            DELETE FROM COMPRADORES WHERE ID_COMPRADOR = 'GUST';
            RAISE EXCEPTION 'TESTE 3A - FAIL';
        EXCEPTION
            WHEN foreign_key_violation THEN
                RAISE NOTICE 'TESTE 3A - OK';
        END;

        /* TESTE 3B - TENTA DELETAR COMPRADOR LORE - DEVE PASSAR */
        BEGIN
            DELETE FROM COMPRADORES WHERE ID_COMPRADOR = 'LORE';
            RAISE NOTICE 'TESTE 3B - OK';
        EXCEPTION
            WHEN OTHERS THEN
                RAISE NOTICE 'TESTE 3A - FAIL';
        END;
    END;
$$;

DO $$
    BEGIN
        RAISE NOTICE 'TESTE 4 - TESTAR INSERIR EM TABELA TRANSACOES';

        /* TESTE 4A - TENTA INSERIR PRODUTO EM VENDA EXISTENTE - DEVE PASSAR */
        BEGIN
            INSERT INTO TRANSACOES VALUES ('ARGILA', 1, 1.0); /* VENDA 1 - 1x ARGILA - TOTAL 10   */
            RAISE NOTICE 'TESTE 4A - OK';
        EXCEPTION
            WHEN OTHERS THEN
                RAISE EXCEPTION 'TESTE 4A - FAIL';
        END;

        /* TESTE 4B - TENTA INSERIR PRODUTO DUPLICADO - DEVE FALHAR*/
        BEGIN
            INSERT INTO TRANSACOES VALUES ('ARGILA', 1, 1.0); /* VENDA 1 - 1x ARGILA - TOTAL 10   */
            RAISE EXCEPTION 'TESTE 4B - FAIL';
        EXCEPTION
            WHEN unique_violation THEN
                RAISE NOTICE 'TESTE 4B - OK';
        END;
        
        /* TESTE 4C - TENTA INSERIR PRODUTO EM VENDA INEXISTENTE - DEVE FALHAR*/
        BEGIN
            INSERT INTO TRANSACOES VALUES ('ARGILA', 6, 1.0); /* VENDA 1 - 1x ARGILA - TOTAL 10   */
            RAISE EXCEPTION 'TESTE 4C - FAIL';
        EXCEPTION
            WHEN foreign_key_violation THEN
                RAISE NOTICE 'TESTE 4C - OK';
        END;
    END;
$$;

DO $$
    DECLARE
        ROW_COUNT int = 0;
    BEGIN
        RAISE NOTICE 'TESTE 5 - CASCADE NA TABELA DE VENDAS';
        DELETE FROM VENDAS WHERE ID_VENDA = 1;
        SELECT COUNT(*) INTO ROW_COUNT FROM TRANSACOES;
        IF ROW_COUNT = 1 THEN
            RAISE NOTICE 'TESTE 5A - OK';
        ELSE
            RAISE EXCEPTION 'TESTE 5A - FAIL';
        END IF;
    END;
$$;
